### ISSUE TITLE
Make this pic transparrent

### ISSUE THREAD

**Issue by Danek309044** [hewol/hewol.github.io#1]
**Recomended website to do it https://remove.bg/**

Pic:
https://github.com/hewol/hewol.github.io/blob/main/assets/img/aeros-pic.jpg

**Comment by XanuduBuster** [comment]
I am gonna do it...

**Comment by XanuduBuster** [comment]
![aeros-pic-removebg-preview](https://github.com/hewol/hewol.github.io/assets/133562760/b2394535-d62e-4346-8b21-dc0916c4f353)

Is this Ok?

**Comment by Danek309044** [comment]
Yep
And after uploading it to github, copy the img url and replace the `io.remove.bg/...` in the **aerOS** readme

**Comment by XanuduBuster** [comment]
yeah, of course

**Comment by XanuduBuster** [comment]
wait, I have to convert the file format from png to jpg

**Comment by Danek309044** [comment]
The image should download in png so just upload it into the ./asset/img/ folder

**Comment by XanuduBuster** [comment]
Ok!

**Comment by XanuduBuster** [comment]
Now check if its now ok or not? If its ok then I will close this issue, If not please tell me....

**Comment by Danek309044** [comment]
It's ok!
