### ISSUE TITLE
Images are still cropped on mobile devices

### ISSUE THREAD

**Issue by Danek309044** [hewol/hewol.github.io#3]
# 1st iPhone XR | 2nd Pixel 5 | 3rd Galaxy A51/A71 | 4th iPhone SE

![xr](https://github.com/hewol/hewol.github.io/assets/90469284/5ee49b25-027b-4e56-bb81-c2ac3d0403d4) ![pixel](https://github.com/hewol/hewol.github.io/assets/90469284/89e9d5e9-c681-482c-a2aa-6d943b5155e6)
![galaxy](https://github.com/hewol/hewol.github.io/assets/90469284/55a83659-f99d-4e7e-bbb6-d544db8524d7) ![se](https://github.com/hewol/hewol.github.io/assets/90469284/18d6e886-607d-4326-8708-e985dfed7a00)

**Comment by XanuduBuster** [comment]
Its a issue...

**Comment by XanuduBuster** [comment]
And there might be no way to fix it...

**Comment by debarkak** [comment]
@XanuduBuster @Danek309044 This issue will be fixed after few weeks.
